name: sys-boost-toolkit # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: System Booster Pack
summary: Optimize and clean your system performance.
description: Remove junk files, monitor resources, and speed up your device using an all-in-one system utility built for stability and performance.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  sys-boost-toolkit:
    command: bin/sys-boost-toolkit-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  sys-boost-toolkit:
    plugin: dump
    source: .
    organize:
      sys-boost-toolkit-bin: bin/
